PREFIX ex:   <http://www.example.com/>
PREFIX oa:   <http://www.w3.org/ns/oa#>
PREFIX as:   <https://www.w3.org/ns/activitystreams#>

CONSTRUCT {
  ex:kb_scenario_$num
      a ex:KnowledgeBase, oa:AnnotationPage ;
      as:items ?fr .
}
WHERE {
  ?fr a ex:FormalRepresentation ;
      oa:hasTarget ex:scenario_$num .
}