PREFIX ex:   <http://www.example.com/>
PREFIX oa:   <http://www.w3.org/ns/oa#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX as:   <https://www.w3.org/ns/activitystreams#>

CONSTRUCT {
  ex:FOLKnowledgeBase
      a ex:KnowledgeBase, oa:AnnotationPage ;
      as:items ?fr .
}
WHERE {
  ?fr a ex:FormalRepresentation ;
      ex:hasFormat "First-order logic" .
}