SELECT DISTINCT ?expert
WHERE {
    {
        FILTER( "$transitive" = "yes")
        $expert foaf:knows* ?expert .
        ?expert a ex:DomainExpert .
    }
    UNION
    {
        FILTER("$transitive" = "no")
        BIND($expert AS ?expert)
    }
}